// ─── STEG National Grid Constants ────────────────────────────────────────────
export const STEG = {
  TOTAL_CAPACITY_MW: 5944,
  EFFECTIVE_CAPACITY_MW: 4636,
  GRID_LOSSES_PCT: 22,
  RECORD_PEAK_MW: 4888,
  RECORD_PEAK_DATE: 'August 14, 2024',
  RECORD_PEAK_DATETIME: '2024-08-14T15:41:00',
  BASELINE_DEMAND_MW: 2800,
  Q3_AVG_DEMAND_MW: 3800,
  ALGERIA_DEPENDENCY_PCT: 14,
  ALGERIA_DEFICIT_MW: 252,
  RENEWABLE_PCT: 6,
  FOSSIL_PCT: 93.7,
  ANNUAL_GENERATION_GWH: 19395,
  POPULATION: 11_800_000,
  CARBON_EMISSION_FACTOR: 0.468, // kg CO₂ / kWh
  ENERGY_INDEPENDENCE_2023: 48,
  ENERGY_INDEPENDENCE_2024: 41,
}

// ─── Risk Level Configuration ─────────────────────────────────────────────────
export const RISK_ORDER = {
  CRITICAL: 4,
  HIGH: 3,
  ELEVATED: 2,
  NOMINAL: 1,
}

export const RISK_COLORS = {
  CRITICAL: '#ff3333',
  HIGH: '#ff9500',
  ELEVATED: '#ffd700',
  NOMINAL: '#00ff88',
}

export const RISK_BG = {
  CRITICAL: 'rgba(255, 51, 51, 0.08)',
  HIGH: 'rgba(255, 149, 0, 0.08)',
  ELEVATED: 'rgba(255, 215, 0, 0.08)',
  NOMINAL: 'rgba(0, 255, 136, 0.08)',
}

export const RISK_BORDER = {
  CRITICAL: 'rgba(255, 51, 51, 0.35)',
  HIGH: 'rgba(255, 149, 0, 0.35)',
  ELEVATED: 'rgba(255, 215, 0, 0.35)',
  NOMINAL: 'rgba(0, 255, 136, 0.25)',
}

// ─── All 24 Tunisian Governorates ─────────────────────────────────────────────
// First 5 have real backend data; the rest use mock data
// installed_capacity_mw : nameplate renewable capacity (≥ baseline_mw)
// avg_demand_mw         : average electrical consumption for the governorate
// peak_demand_mw        : historical peak demand recorded
export const GOVERNORATES = [
  // ── Real backend data ──
  {
    name: 'Bizerte',
    lat: 37.2744, lon: 9.8739,
    source: 'Wind',
    baseline_mw: 97.0,
    rotor_area: 7854.0,
    efficiency: 0.40,
    hasBackend: true,
    region: 'North',
    mock_mw: 87.3,
    mock_risk: 'NOMINAL',
    mock_wind: 8.2,
    mock_irradiance: 420,
    installed_capacity_mw: 120,
    avg_demand_mw: 178,
    peak_demand_mw: 248,
  },
  {
    name: 'Nabeul',
    lat: 36.4561, lon: 10.7376,
    source: 'Wind',
    baseline_mw: 55.0,
    rotor_area: 4418.0,
    efficiency: 0.40,
    hasBackend: true,
    region: 'North-East',
    mock_mw: 42.1,
    mock_risk: 'ELEVATED',
    mock_wind: 6.5,
    mock_irradiance: 580,
    installed_capacity_mw: 75,
    avg_demand_mw: 142,
    peak_demand_mw: 198,
  },
  {
    name: 'Tozeur',
    lat: 33.9197, lon: 8.1335,
    source: 'Solar',
    baseline_mw: 20.0,
    panel_area: 120_000.0,
    efficiency: 0.18,
    hasBackend: true,
    region: 'South-West',
    mock_mw: 19.2,
    mock_risk: 'NOMINAL',
    mock_wind: 3.1,
    mock_irradiance: 820,
    installed_capacity_mw: 25,
    avg_demand_mw: 44,
    peak_demand_mw: 63,
  },
  {
    name: 'Béja',
    lat: 36.7256, lon: 9.1817,
    source: 'Hydro',
    baseline_mw: 33.0,
    hasBackend: true,
    region: 'North-West',
    mock_mw: 33.0,
    mock_risk: 'NOMINAL',
    mock_wind: 5.8,
    mock_irradiance: 390,
    installed_capacity_mw: 40,
    avg_demand_mw: 74,
    peak_demand_mw: 103,
  },
  {
    name: 'Sidi Bouzid',
    lat: 35.0382, lon: 9.4858,
    source: 'Solar',
    baseline_mw: 100.0,
    panel_area: 600_000.0,
    efficiency: 0.18,
    hasBackend: true,
    region: 'Centre',
    mock_mw: 68.4,
    mock_risk: 'HIGH',
    mock_wind: 4.2,
    mock_irradiance: 750,
    installed_capacity_mw: 130,
    avg_demand_mw: 92,
    peak_demand_mw: 128,
  },
  // ── Mock data governorates ──
  {
    name: 'Tunis',
    lat: 36.8190, lon: 10.1658,
    source: 'Mixed',
    baseline_mw: 450,
    rotor_area: 15708.0,
    efficiency: 0.35,
    hasBackend: true,
    region: 'North-East',
    mock_mw: 380,
    mock_risk: 'CRITICAL',
    mock_wind: 5.1,
    mock_irradiance: 510,
    installed_capacity_mw: 500,
    avg_demand_mw: 820,
    peak_demand_mw: 1120,
  },
  {
    name: 'Ariana',
    lat: 36.8665, lon: 10.1647,
    source: 'Mixed',
    baseline_mw: 120,
    rotor_area: 7854.0,
    efficiency: 0.35,
    hasBackend: true,
    region: 'North-East',
    mock_mw: 95,
    mock_risk: 'HIGH',
    mock_wind: 4.8,
    mock_irradiance: 495,
    installed_capacity_mw: 135,
    avg_demand_mw: 182,
    peak_demand_mw: 252,
  },
  {
    name: 'Ben Arous',
    lat: 36.7533, lon: 10.2281,
    source: 'Mixed',
    baseline_mw: 180,
    rotor_area: 7854.0,
    efficiency: 0.35,
    hasBackend: true,
    region: 'North-East',
    mock_mw: 155,
    mock_risk: 'ELEVATED',
    mock_wind: 4.5,
    mock_irradiance: 520,
    installed_capacity_mw: 200,
    avg_demand_mw: 225,
    peak_demand_mw: 312,
  },
  {
    name: 'Manouba',
    lat: 36.8092, lon: 9.9885,
    source: 'Mixed',
    baseline_mw: 95,
    rotor_area: 5027.0,
    efficiency: 0.35,
    hasBackend: true,
    region: 'North',
    mock_mw: 91,
    mock_risk: 'NOMINAL',
    mock_wind: 5.5,
    mock_irradiance: 480,
    installed_capacity_mw: 100,
    avg_demand_mw: 132,
    peak_demand_mw: 182,
  },
  {
    name: 'Zaghouan',
    lat: 36.4029, lon: 10.1427,
    source: 'Hydro',
    baseline_mw: 28,
    hasBackend: true,
    region: 'North-East',
    mock_mw: 26.5,
    mock_risk: 'NOMINAL',
    mock_wind: 4.2,
    mock_irradiance: 550,
    installed_capacity_mw: 35,
    avg_demand_mw: 54,
    peak_demand_mw: 74,
  },
  {
    name: 'Jendouba',
    lat: 36.5012, lon: 8.7803,
    source: 'Hydro',
    baseline_mw: 42,
    hasBackend: true,
    region: 'North-West',
    mock_mw: 40.5,
    mock_risk: 'NOMINAL',
    mock_wind: 6.1,
    mock_irradiance: 410,
    installed_capacity_mw: 55,
    avg_demand_mw: 96,
    peak_demand_mw: 132,
  },
  {
    name: 'Kef',
    lat: 36.1820, lon: 8.7046,
    source: 'Wind',
    baseline_mw: 45,
    hasBackend: true,
    region: 'North-West',
    mock_mw: 43.2,
    mock_risk: 'NOMINAL',
    mock_wind: 7.8,
    mock_irradiance: 440,
    installed_capacity_mw: 60,
    avg_demand_mw: 68,
    peak_demand_mw: 93,
  },
  {
    name: 'Siliana',
    lat: 36.0842, lon: 9.3748,
    source: 'Wind',
    baseline_mw: 38,
    hasBackend: true,
    region: 'North-West',
    mock_mw: 36.1,
    mock_risk: 'NOMINAL',
    mock_wind: 7.2,
    mock_irradiance: 460,
    installed_capacity_mw: 50,
    avg_demand_mw: 62,
    peak_demand_mw: 86,
  },
  {
    name: 'Sousse',
    lat: 35.8256, lon: 10.6368,
    source: 'Mixed',
    baseline_mw: 220,
    rotor_area: 10000.0,
    efficiency: 0.35,
    hasBackend: true,
    region: 'Centre-East',
    mock_mw: 195,
    mock_risk: 'HIGH',
    mock_wind: 5.0,
    mock_irradiance: 620,
    installed_capacity_mw: 250,
    avg_demand_mw: 258,
    peak_demand_mw: 358,
  },
  {
    name: 'Monastir',
    lat: 35.7643, lon: 10.8113,
    source: 'Solar',
    baseline_mw: 85,
    hasBackend: true,
    region: 'Centre-East',
    mock_mw: 82.3,
    mock_risk: 'NOMINAL',
    mock_wind: 4.6,
    mock_irradiance: 660,
    installed_capacity_mw: 100,
    avg_demand_mw: 174,
    peak_demand_mw: 240,
  },
  {
    name: 'Mahdia',
    lat: 35.5047, lon: 11.0622,
    source: 'Wind',
    baseline_mw: 60,
    hasBackend: true,
    region: 'Centre-East',
    mock_mw: 55.2,
    mock_risk: 'NOMINAL',
    mock_wind: 6.8,
    mock_irradiance: 610,
    installed_capacity_mw: 80,
    avg_demand_mw: 128,
    peak_demand_mw: 175,
  },
  {
    name: 'Sfax',
    lat: 34.7398, lon: 10.7600,
    source: 'Mixed',
    baseline_mw: 280,
    rotor_area: 12000.0,
    efficiency: 0.35,
    hasBackend: true,
    region: 'Centre-East',
    mock_mw: 245,
    mock_risk: 'ELEVATED',
    mock_wind: 5.4,
    mock_irradiance: 680,
    installed_capacity_mw: 320,
    avg_demand_mw: 382,
    peak_demand_mw: 524,
  },
  {
    name: 'Kairouan',
    lat: 35.6781, lon: 10.0963,
    source: 'Solar',
    baseline_mw: 110,
    hasBackend: true,
    region: 'Centre',
    mock_mw: 107.3,
    mock_risk: 'NOMINAL',
    mock_wind: 4.1,
    mock_irradiance: 700,
    installed_capacity_mw: 135,
    avg_demand_mw: 168,
    peak_demand_mw: 232,
  },
  {
    name: 'Kasserine',
    lat: 35.1721, lon: 8.8302,
    source: 'Wind',
    baseline_mw: 75,
    hasBackend: true,
    region: 'Centre-West',
    mock_mw: 71.2,
    mock_risk: 'NOMINAL',
    mock_wind: 8.5,
    mock_irradiance: 560,
    installed_capacity_mw: 95,
    avg_demand_mw: 108,
    peak_demand_mw: 148,
  },
  {
    name: 'Gabès',
    lat: 33.8881, lon: 10.0975,
    source: 'Solar',
    baseline_mw: 90,
    hasBackend: true,
    region: 'South-East',
    mock_mw: 74.5,
    mock_risk: 'ELEVATED',
    mock_wind: 4.0,
    mock_irradiance: 780,
    installed_capacity_mw: 110,
    avg_demand_mw: 132,
    peak_demand_mw: 178,
  },
  {
    name: 'Médenine',
    lat: 33.3549, lon: 10.5055,
    source: 'Solar',
    baseline_mw: 65,
    hasBackend: true,
    region: 'South-East',
    mock_mw: 62.8,
    mock_risk: 'NOMINAL',
    mock_wind: 3.8,
    mock_irradiance: 800,
    installed_capacity_mw: 80,
    avg_demand_mw: 124,
    peak_demand_mw: 168,
  },
  {
    name: 'Tataouine',
    lat: 32.9211, lon: 10.4518,
    source: 'Solar',
    baseline_mw: 40,
    hasBackend: true,
    region: 'South-East',
    mock_mw: 38.9,
    mock_risk: 'NOMINAL',
    mock_wind: 3.5,
    mock_irradiance: 840,
    installed_capacity_mw: 50,
    avg_demand_mw: 50,
    peak_demand_mw: 68,
  },
  {
    name: 'Gafsa',
    lat: 34.4311, lon: 8.7757,
    source: 'Solar',
    baseline_mw: 55,
    hasBackend: true,
    region: 'South-West',
    mock_mw: 52.3,
    mock_risk: 'NOMINAL',
    mock_wind: 3.9,
    mock_irradiance: 800,
    installed_capacity_mw: 70,
    avg_demand_mw: 124,
    peak_demand_mw: 168,
  },
  {
    name: 'Kebili',
    lat: 33.7046, lon: 8.9715,
    source: 'Solar',
    baseline_mw: 35,
    hasBackend: true,
    region: 'South-West',
    mock_mw: 33.4,
    mock_risk: 'NOMINAL',
    mock_wind: 3.6,
    mock_irradiance: 860,
    installed_capacity_mw: 45,
    avg_demand_mw: 48,
    peak_demand_mw: 66,
  },
]

// ─── Source Icons ─────────────────────────────────────────────────────────────
export const SOURCE_ICON = {
  Wind: '🌬',
  Solar: '☀',
  Hydro: '💧',
  Mixed: '⚡',
}

// ─── Source Colors ────────────────────────────────────────────────────────────
export const SOURCE_COLOR = {
  Wind: '#06b6d4',
  Solar: '#ffd700',
  Hydro: '#3b82f6',
  Mixed: '#00ff88',
}

// ─── National Carbon Index (mock baseline) ────────────────────────────────────
export const NATIONAL_CARBON_INDEX = {
  value: 2.31,           // kg CO₂ per capita per day
  unit: 'kg CO₂/cap/day',
  trend: -0.04,          // improving
  target: 1.8,
  max: 4.0,
}

// ─── August 14 2024 Replay Scenario ──────────────────────────────────────────
export const AUG14_SCENARIO = {
  temperature_c: 45,
  demand_delta_pct: 20,
  renewable_output_mw: 280,
  reserve_capacity_mw: 0,
  include_peak_hour_factor: true,
  label: 'August 14, 2024 — Record Crisis',
  description: '4,888 MW demand. 4,636 MW effective capacity. Algeria covered the 252 MW gap.',
}
